name = "regional-income-api"
main = "worker.ts"
compatibility_date = "2024-10-01"
workers_dev = false

# Routes configuration (we'll add this after getting a domain)
# For now, we'll deploy without workers.dev subdomain
